autoplay: false


origins:
        "BENHUR": { 
                store: "Vaultaire", 
                source: "Demowave",
                title: "SineWave",
                store_settings: { 
                        host: "http://sieste-01.syd1.anchor.net.au",
                } 
        }
        "4YL1CF": {
                store: "Vaultaire",
                source: "Ceilometer",
                store_settings: {
                        host: "http://sieste-01.syd1.anchor.net.au",
                },
                title: "Dev Ceilometer",
        }
